// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class AddRequest;
@class AddRequest_Builder;
@class BoundingBox;
@class BoundingBox_Builder;
@class ChangeRequest;
@class ChangeRequest_Builder;
@class DeleteRequest;
@class DeleteRequest_Builder;
@class Plakat;
@class Plakat_Builder;
@class Request;
@class Request_Builder;
@class Response;
@class Response_Builder;
@class ViewRequest;
@class ViewRequest_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface ApiRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Plakat : PBGeneratedMessage {
@private
  BOOL hasLon_:1;
  BOOL hasLat_:1;
  BOOL hasId_:1;
  BOOL hasLastModifiedTime_:1;
  BOOL hasType_:1;
  BOOL hasLastModifiedUser_:1;
  BOOL hasComment_:1;
  BOOL hasImageUrl_:1;
  Float64 lon;
  Float64 lat;
  int32_t id;
  int32_t lastModifiedTime;
  NSString* type;
  NSString* lastModifiedUser;
  NSString* comment;
  NSString* imageUrl;
}
- (BOOL) hasId;
- (BOOL) hasLon;
- (BOOL) hasLat;
- (BOOL) hasType;
- (BOOL) hasLastModifiedUser;
- (BOOL) hasLastModifiedTime;
- (BOOL) hasComment;
- (BOOL) hasImageUrl;
@property (readonly) int32_t id;
@property (readonly) Float64 lon;
@property (readonly) Float64 lat;
@property (readonly, strong) NSString* type;
@property (readonly, strong) NSString* lastModifiedUser;
@property (readonly) int32_t lastModifiedTime;
@property (readonly, strong) NSString* comment;
@property (readonly, strong) NSString* imageUrl;

+ (Plakat*) defaultInstance;
- (Plakat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Plakat_Builder*) builder;
+ (Plakat_Builder*) builder;
+ (Plakat_Builder*) builderWithPrototype:(Plakat*) prototype;
- (Plakat_Builder*) toBuilder;

+ (Plakat*) parseFromData:(NSData*) data;
+ (Plakat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Plakat*) parseFromInputStream:(NSInputStream*) input;
+ (Plakat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Plakat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Plakat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Plakat_Builder : PBGeneratedMessage_Builder {
@private
  Plakat* result;
}

- (Plakat*) defaultInstance;

- (Plakat_Builder*) clear;
- (Plakat_Builder*) clone;

- (Plakat*) build;
- (Plakat*) buildPartial;

- (Plakat_Builder*) mergeFrom:(Plakat*) other;
- (Plakat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Plakat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (Plakat_Builder*) setId:(int32_t) value;
- (Plakat_Builder*) clearId;

- (BOOL) hasLon;
- (Float64) lon;
- (Plakat_Builder*) setLon:(Float64) value;
- (Plakat_Builder*) clearLon;

- (BOOL) hasLat;
- (Float64) lat;
- (Plakat_Builder*) setLat:(Float64) value;
- (Plakat_Builder*) clearLat;

- (BOOL) hasType;
- (NSString*) type;
- (Plakat_Builder*) setType:(NSString*) value;
- (Plakat_Builder*) clearType;

- (BOOL) hasLastModifiedUser;
- (NSString*) lastModifiedUser;
- (Plakat_Builder*) setLastModifiedUser:(NSString*) value;
- (Plakat_Builder*) clearLastModifiedUser;

- (BOOL) hasLastModifiedTime;
- (int32_t) lastModifiedTime;
- (Plakat_Builder*) setLastModifiedTime:(int32_t) value;
- (Plakat_Builder*) clearLastModifiedTime;

- (BOOL) hasComment;
- (NSString*) comment;
- (Plakat_Builder*) setComment:(NSString*) value;
- (Plakat_Builder*) clearComment;

- (BOOL) hasImageUrl;
- (NSString*) imageUrl;
- (Plakat_Builder*) setImageUrl:(NSString*) value;
- (Plakat_Builder*) clearImageUrl;
@end

@interface BoundingBox : PBGeneratedMessage {
@private
  BOOL hasNorth_:1;
  BOOL hasEast_:1;
  BOOL hasSouth_:1;
  BOOL hasWest_:1;
  Float64 north;
  Float64 east;
  Float64 south;
  Float64 west;
}
- (BOOL) hasNorth;
- (BOOL) hasEast;
- (BOOL) hasSouth;
- (BOOL) hasWest;
@property (readonly) Float64 north;
@property (readonly) Float64 east;
@property (readonly) Float64 south;
@property (readonly) Float64 west;

+ (BoundingBox*) defaultInstance;
- (BoundingBox*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BoundingBox_Builder*) builder;
+ (BoundingBox_Builder*) builder;
+ (BoundingBox_Builder*) builderWithPrototype:(BoundingBox*) prototype;
- (BoundingBox_Builder*) toBuilder;

+ (BoundingBox*) parseFromData:(NSData*) data;
+ (BoundingBox*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BoundingBox*) parseFromInputStream:(NSInputStream*) input;
+ (BoundingBox*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BoundingBox*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BoundingBox*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BoundingBox_Builder : PBGeneratedMessage_Builder {
@private
  BoundingBox* result;
}

- (BoundingBox*) defaultInstance;

- (BoundingBox_Builder*) clear;
- (BoundingBox_Builder*) clone;

- (BoundingBox*) build;
- (BoundingBox*) buildPartial;

- (BoundingBox_Builder*) mergeFrom:(BoundingBox*) other;
- (BoundingBox_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BoundingBox_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNorth;
- (Float64) north;
- (BoundingBox_Builder*) setNorth:(Float64) value;
- (BoundingBox_Builder*) clearNorth;

- (BOOL) hasEast;
- (Float64) east;
- (BoundingBox_Builder*) setEast:(Float64) value;
- (BoundingBox_Builder*) clearEast;

- (BOOL) hasSouth;
- (Float64) south;
- (BoundingBox_Builder*) setSouth:(Float64) value;
- (BoundingBox_Builder*) clearSouth;

- (BOOL) hasWest;
- (Float64) west;
- (BoundingBox_Builder*) setWest:(Float64) value;
- (BoundingBox_Builder*) clearWest;
@end

@interface ViewRequest : PBGeneratedMessage {
@private
  BOOL hasFilterType_:1;
  BOOL hasViewBox_:1;
  NSString* filterType;
  BoundingBox* viewBox;
}
- (BOOL) hasFilterType;
- (BOOL) hasViewBox;
@property (readonly, strong) NSString* filterType;
@property (readonly, strong) BoundingBox* viewBox;

+ (ViewRequest*) defaultInstance;
- (ViewRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ViewRequest_Builder*) builder;
+ (ViewRequest_Builder*) builder;
+ (ViewRequest_Builder*) builderWithPrototype:(ViewRequest*) prototype;
- (ViewRequest_Builder*) toBuilder;

+ (ViewRequest*) parseFromData:(NSData*) data;
+ (ViewRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ViewRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ViewRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ViewRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ViewRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ViewRequest_Builder : PBGeneratedMessage_Builder {
@private
  ViewRequest* result;
}

- (ViewRequest*) defaultInstance;

- (ViewRequest_Builder*) clear;
- (ViewRequest_Builder*) clone;

- (ViewRequest*) build;
- (ViewRequest*) buildPartial;

- (ViewRequest_Builder*) mergeFrom:(ViewRequest*) other;
- (ViewRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ViewRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFilterType;
- (NSString*) filterType;
- (ViewRequest_Builder*) setFilterType:(NSString*) value;
- (ViewRequest_Builder*) clearFilterType;

- (BOOL) hasViewBox;
- (BoundingBox*) viewBox;
- (ViewRequest_Builder*) setViewBox:(BoundingBox*) value;
- (ViewRequest_Builder*) setViewBoxBuilder:(BoundingBox_Builder*) builderForValue;
- (ViewRequest_Builder*) mergeViewBox:(BoundingBox*) value;
- (ViewRequest_Builder*) clearViewBox;
@end

@interface ChangeRequest : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasType_:1;
  BOOL hasComment_:1;
  BOOL hasImageUrl_:1;
  int32_t id;
  NSString* type;
  NSString* comment;
  NSString* imageUrl;
}
- (BOOL) hasId;
- (BOOL) hasType;
- (BOOL) hasComment;
- (BOOL) hasImageUrl;
@property (readonly) int32_t id;
@property (readonly, strong) NSString* type;
@property (readonly, strong) NSString* comment;
@property (readonly, strong) NSString* imageUrl;

+ (ChangeRequest*) defaultInstance;
- (ChangeRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChangeRequest_Builder*) builder;
+ (ChangeRequest_Builder*) builder;
+ (ChangeRequest_Builder*) builderWithPrototype:(ChangeRequest*) prototype;
- (ChangeRequest_Builder*) toBuilder;

+ (ChangeRequest*) parseFromData:(NSData*) data;
+ (ChangeRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangeRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ChangeRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangeRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChangeRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChangeRequest_Builder : PBGeneratedMessage_Builder {
@private
  ChangeRequest* result;
}

- (ChangeRequest*) defaultInstance;

- (ChangeRequest_Builder*) clear;
- (ChangeRequest_Builder*) clone;

- (ChangeRequest*) build;
- (ChangeRequest*) buildPartial;

- (ChangeRequest_Builder*) mergeFrom:(ChangeRequest*) other;
- (ChangeRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChangeRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (ChangeRequest_Builder*) setId:(int32_t) value;
- (ChangeRequest_Builder*) clearId;

- (BOOL) hasType;
- (NSString*) type;
- (ChangeRequest_Builder*) setType:(NSString*) value;
- (ChangeRequest_Builder*) clearType;

- (BOOL) hasComment;
- (NSString*) comment;
- (ChangeRequest_Builder*) setComment:(NSString*) value;
- (ChangeRequest_Builder*) clearComment;

- (BOOL) hasImageUrl;
- (NSString*) imageUrl;
- (ChangeRequest_Builder*) setImageUrl:(NSString*) value;
- (ChangeRequest_Builder*) clearImageUrl;
@end

@interface DeleteRequest : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  int32_t id;
}
- (BOOL) hasId;
@property (readonly) int32_t id;

+ (DeleteRequest*) defaultInstance;
- (DeleteRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DeleteRequest_Builder*) builder;
+ (DeleteRequest_Builder*) builder;
+ (DeleteRequest_Builder*) builderWithPrototype:(DeleteRequest*) prototype;
- (DeleteRequest_Builder*) toBuilder;

+ (DeleteRequest*) parseFromData:(NSData*) data;
+ (DeleteRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeleteRequest*) parseFromInputStream:(NSInputStream*) input;
+ (DeleteRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeleteRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DeleteRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DeleteRequest_Builder : PBGeneratedMessage_Builder {
@private
  DeleteRequest* result;
}

- (DeleteRequest*) defaultInstance;

- (DeleteRequest_Builder*) clear;
- (DeleteRequest_Builder*) clone;

- (DeleteRequest*) build;
- (DeleteRequest*) buildPartial;

- (DeleteRequest_Builder*) mergeFrom:(DeleteRequest*) other;
- (DeleteRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DeleteRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (DeleteRequest_Builder*) setId:(int32_t) value;
- (DeleteRequest_Builder*) clearId;
@end

@interface AddRequest : PBGeneratedMessage {
@private
  BOOL hasLon_:1;
  BOOL hasLat_:1;
  BOOL hasType_:1;
  BOOL hasComment_:1;
  BOOL hasImageUrl_:1;
  Float64 lon;
  Float64 lat;
  NSString* type;
  NSString* comment;
  NSString* imageUrl;
}
- (BOOL) hasLon;
- (BOOL) hasLat;
- (BOOL) hasType;
- (BOOL) hasComment;
- (BOOL) hasImageUrl;
@property (readonly) Float64 lon;
@property (readonly) Float64 lat;
@property (readonly, strong) NSString* type;
@property (readonly, strong) NSString* comment;
@property (readonly, strong) NSString* imageUrl;

+ (AddRequest*) defaultInstance;
- (AddRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AddRequest_Builder*) builder;
+ (AddRequest_Builder*) builder;
+ (AddRequest_Builder*) builderWithPrototype:(AddRequest*) prototype;
- (AddRequest_Builder*) toBuilder;

+ (AddRequest*) parseFromData:(NSData*) data;
+ (AddRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AddRequest*) parseFromInputStream:(NSInputStream*) input;
+ (AddRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AddRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AddRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AddRequest_Builder : PBGeneratedMessage_Builder {
@private
  AddRequest* result;
}

- (AddRequest*) defaultInstance;

- (AddRequest_Builder*) clear;
- (AddRequest_Builder*) clone;

- (AddRequest*) build;
- (AddRequest*) buildPartial;

- (AddRequest_Builder*) mergeFrom:(AddRequest*) other;
- (AddRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AddRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLon;
- (Float64) lon;
- (AddRequest_Builder*) setLon:(Float64) value;
- (AddRequest_Builder*) clearLon;

- (BOOL) hasLat;
- (Float64) lat;
- (AddRequest_Builder*) setLat:(Float64) value;
- (AddRequest_Builder*) clearLat;

- (BOOL) hasType;
- (NSString*) type;
- (AddRequest_Builder*) setType:(NSString*) value;
- (AddRequest_Builder*) clearType;

- (BOOL) hasComment;
- (NSString*) comment;
- (AddRequest_Builder*) setComment:(NSString*) value;
- (AddRequest_Builder*) clearComment;

- (BOOL) hasImageUrl;
- (NSString*) imageUrl;
- (AddRequest_Builder*) setImageUrl:(NSString*) value;
- (AddRequest_Builder*) clearImageUrl;
@end

@interface Request : PBGeneratedMessage {
@private
  BOOL hasUsername_:1;
  BOOL hasPassword_:1;
  BOOL hasViewRequest_:1;
  NSString* username;
  NSString* password;
  ViewRequest* viewRequest;
  NSMutableArray * addArray;
  NSMutableArray * changeArray;
  NSMutableArray * deleteArray;
}
- (BOOL) hasUsername;
- (BOOL) hasPassword;
- (BOOL) hasViewRequest;
@property (readonly, strong) NSString* username;
@property (readonly, strong) NSString* password;
@property (readonly, strong) ViewRequest* viewRequest;
@property (readonly, strong) NSArray * add;
@property (readonly, strong) NSArray * change;
@property (readonly, strong) NSArray * delete;
- (AddRequest*)addAtIndex:(NSUInteger)index;
- (ChangeRequest*)changeAtIndex:(NSUInteger)index;
- (DeleteRequest*)deleteAtIndex:(NSUInteger)index;

+ (Request*) defaultInstance;
- (Request*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Request_Builder*) builder;
+ (Request_Builder*) builder;
+ (Request_Builder*) builderWithPrototype:(Request*) prototype;
- (Request_Builder*) toBuilder;

+ (Request*) parseFromData:(NSData*) data;
+ (Request*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Request*) parseFromInputStream:(NSInputStream*) input;
+ (Request*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Request*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Request*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Request_Builder : PBGeneratedMessage_Builder {
@private
  Request* result;
}

- (Request*) defaultInstance;

- (Request_Builder*) clear;
- (Request_Builder*) clone;

- (Request*) build;
- (Request*) buildPartial;

- (Request_Builder*) mergeFrom:(Request*) other;
- (Request_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Request_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUsername;
- (NSString*) username;
- (Request_Builder*) setUsername:(NSString*) value;
- (Request_Builder*) clearUsername;

- (BOOL) hasPassword;
- (NSString*) password;
- (Request_Builder*) setPassword:(NSString*) value;
- (Request_Builder*) clearPassword;

- (BOOL) hasViewRequest;
- (ViewRequest*) viewRequest;
- (Request_Builder*) setViewRequest:(ViewRequest*) value;
- (Request_Builder*) setViewRequestBuilder:(ViewRequest_Builder*) builderForValue;
- (Request_Builder*) mergeViewRequest:(ViewRequest*) value;
- (Request_Builder*) clearViewRequest;

- (NSMutableArray *)add;
- (AddRequest*)addAtIndex:(NSUInteger)index;
- (Request_Builder *)addAdd:(AddRequest*)value;
- (Request_Builder *)setAddArray:(NSArray *)array;
- (Request_Builder *)clearAdd;

- (NSMutableArray *)change;
- (ChangeRequest*)changeAtIndex:(NSUInteger)index;
- (Request_Builder *)addChange:(ChangeRequest*)value;
- (Request_Builder *)setChangeArray:(NSArray *)array;
- (Request_Builder *)clearChange;

- (NSMutableArray *)delete;
- (DeleteRequest*)deleteAtIndex:(NSUInteger)index;
- (Request_Builder *)addDelete:(DeleteRequest*)value;
- (Request_Builder *)setDeleteArray:(NSArray *)array;
- (Request_Builder *)clearDelete;
@end

@interface Response : PBGeneratedMessage {
@private
  BOOL hasAddedCount_:1;
  BOOL hasChangedCount_:1;
  BOOL hasDeletedCount_:1;
  int32_t addedCount;
  int32_t changedCount;
  int32_t deletedCount;
  NSMutableArray * plakateArray;
}
- (BOOL) hasAddedCount;
- (BOOL) hasChangedCount;
- (BOOL) hasDeletedCount;
@property (readonly, strong) NSArray * plakate;
@property (readonly) int32_t addedCount;
@property (readonly) int32_t changedCount;
@property (readonly) int32_t deletedCount;
- (Plakat*)plakateAtIndex:(NSUInteger)index;

+ (Response*) defaultInstance;
- (Response*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Response_Builder*) builder;
+ (Response_Builder*) builder;
+ (Response_Builder*) builderWithPrototype:(Response*) prototype;
- (Response_Builder*) toBuilder;

+ (Response*) parseFromData:(NSData*) data;
+ (Response*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Response*) parseFromInputStream:(NSInputStream*) input;
+ (Response*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Response*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Response*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Response_Builder : PBGeneratedMessage_Builder {
@private
  Response* result;
}

- (Response*) defaultInstance;

- (Response_Builder*) clear;
- (Response_Builder*) clone;

- (Response*) build;
- (Response*) buildPartial;

- (Response_Builder*) mergeFrom:(Response*) other;
- (Response_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Response_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)plakate;
- (Plakat*)plakateAtIndex:(NSUInteger)index;
- (Response_Builder *)addPlakate:(Plakat*)value;
- (Response_Builder *)setPlakateArray:(NSArray *)array;
- (Response_Builder *)clearPlakate;

- (BOOL) hasAddedCount;
- (int32_t) addedCount;
- (Response_Builder*) setAddedCount:(int32_t) value;
- (Response_Builder*) clearAddedCount;

- (BOOL) hasChangedCount;
- (int32_t) changedCount;
- (Response_Builder*) setChangedCount:(int32_t) value;
- (Response_Builder*) clearChangedCount;

- (BOOL) hasDeletedCount;
- (int32_t) deletedCount;
- (Response_Builder*) setDeletedCount:(int32_t) value;
- (Response_Builder*) clearDeletedCount;
@end

